### ISSUE TITLE
'&' symbol block the params

### ISSUE THREAD

**Issue by Ravichandrane** [MacPaw/Google-Analytics-for-OS-X#3]
Hi,

I tried to use the GA for macOS and spent quite a bit of time but I have a problem with the symbol '&'. I want to send something like that to the GA : `/hello-world/something?sort=hello&type=toto` but GA return only `/hello-world/something?sort=hello`. 

Many thanks,
Cheers.

**Comment by atjason** [comment]
@Ravichandrane Please encode & to %26 before send as category/event/label of GA. BTW, I would suggest you encode all the strings set to GA, e.g., /?&, etc.

Let me know it works or not.

**Comment by Ravichandrane** [comment]
Hi @atjason Thanks for your reply. 
I already try to encode & to %26 but GA return the encode character not '&'. 

Thanks,
Cheers.

**Comment by atjason** [comment]
Hi @Ravichandrane Welcome :)

**Comment by Ravichandrane** [comment]
@atjason I want GA return the & symbol not the encode character %26... So it's not work :(

**Comment by atjason** [comment]
@Ravichandrane Seems you need to @ the owner of this project.

**Comment by Ravichandrane** [comment]
@atjason Sorry, I don't understand what do you mean ?

**Comment by atjason** [comment]
@Ravichandrane I mean, I'm not the owner of the project, can't help more.

**Comment by Ravichandrane** [comment]
@atjason I will create a sample project and share with you before Monday.

**Comment by Ravichandrane** [comment]
@atjason here is the github with the sample project: https://github.com/Ravichandrane/macOSGA

Thanks for your help,
Cheers.

**Comment by atjason** [comment]
@Ravichandrane Please @ the contributors of this project for more help.

![2231571](https://cloud.githubusercontent.com/assets/803199/19239618/795d0c94-8f39-11e6-918e-cef22492afde.jpg)

**Comment by Ravichandrane** [comment]
@atjason Just added Zyafa & ivira

**Comment by ivira** [comment]
Hello @Ravichandrane,

Thanks for pointing out, fixed. I wonder why do you use such screen names?

@atjason thx for the support.

**Comment by Ravichandrane** [comment]
Hi @ivira thanks for the fixe. 
Is that normal when I try `pod update`  nothing happen ?
I'm using NSSelector to filter some content on the app I'm working and the client wants to track all the params selected by the user.

**Comment by ivira** [comment]
Can't update right now. Please wait a bit.

**Comment by Ravichandrane** [comment]
Okay @ivira :)

**Comment by ivira** [comment]
Updated pod. Check it out.

**Comment by Ravichandrane** [comment]
hey @ivira thanks :)
